Winners/Winners/Controllers/WinnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Winners.Models;
using Winners.ViewModels;
namespace Winners.Controllers
{
    public class WinnersController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Winners
        public ActionResult Index()
        {
            //TODO:Get a list of all the winners
            var getWinners = (from a in db.answers
                              select a);
            ViewBag.TotalUsers = getWinners.Count() + 1;
            return View(getWinners);
        }

        //get winners

        [HttpPost]
        public JsonResult getName()
        {
            int vw = 0;
            List<VMWinners> vmwin = new List<VMWinners>();
            var getWinners = from a in db.answers
                             select a;
            foreach (var itm in getWinners)
            {
                vmwin.Add(new VMWinners { Id = vw + 1, g_name = itm.g_name, g_tel = itm.g_tel });
                vw += 1;
            }

            Random rnd = new Random();
            int Random = rnd.Next(1, getWinners.Count());
            var getWinners2 = (from b in vmwin
                               where b.Id == Random
                               select b).FirstOrDefault();

            return Json(getWinners2, JsonRequestBehavior.AllowGet);
        }

        //angularjs get all winners
        public JsonResult getWinners()
        {
            //var data = (from a in db.answers
            //                  select a).Distinct().Take(500);
            
            //Here we use this code to remove any duplicates in the name
            var mydata = db.answers.GroupBy(x => x.g_name).Select(y => y.FirstOrDefault());
            return Json(new { data = mydata, total = mydata.Count() }, JsonRequestBehavior.AllowGet );
        }

        //show winners
        public ActionResult showAllWinners()
        {
            return View();
        }

        public JsonResult getEmployeeByNo(string name)
        {
            try
            {
                
                var winner = from a in db.winners
                             where a.g_name.Contains(name)
                             select a;
                    return Json(winner, JsonRequestBehavior.AllowGet);
                
            }
            catch (Exception exp)
            {
                return Json("Error in getting record !", JsonRequestBehavior.AllowGet);
            }

        }

        /// <summary>  
        /// Override the JSON Result with Max integer JSON lenght  
        /// </summary>  
        /// <param name="data">Data</param>  
        /// <param name="contentType">Content Type</param>  
        /// <param name="contentEncoding">Content Encoding</param>  
        /// <param name="behavior">Behavior</param>  
        /// <returns>As JsonResult</returns>  
        protected override JsonResult Json(object data, string contentType,
            Encoding contentEncoding, JsonRequestBehavior behavior)
        {
            return new JsonResult()
            {
                Data = data,
                ContentType = contentType,
                ContentEncoding = contentEncoding,
                JsonRequestBehavior = behavior,
                MaxJsonLength = Int32.MaxValue
            };
        }
    }
}

Winners/Winners/Views/Winners/Index.cshtml
@model IEnumerable<Winners.Models.tbl_gust_Answers>
@{
    ViewBag.Title = "Index";
}

<style>
    #tbl tr td{
        border-bottom:1px solid #222;
        padding-top:10px;
    }
    .btn{
        width:100px;
    }

    .wname{
        font-weight:bold;
        color:#000;
        font-size:20px;
        padding-right:10px;
    }
</style>
<div class="row "style="position:relative;height:300px;margin-top:100px;">
<div style="position:absolute;top:50%;margin-top:-100px;left:50%;margin-left:-100px;width:200px;height:200px;">
    <img src="~/Content/logo.png" style="width:200px;height:200px;" />
</div>
</div>

<h2>أسماء الفائزين بالمسابقة الإسبوعية لمهرجان صلالة السياحي 2016</h2>
<div class="row" ng-controller="myController">
    <div class="col-md-12" style="font-weight:bold;font-size:20px;color:green;">
        إجمالي عدد المشاركين:{{TotalWinners}}
    </div>


    <div class="row">
        <div class="col-md-7 alert alert-success" role="alert">
            <div>
                <table>
                    <tr>
                        <td>البحث:</td>
                        <td><input type="text" ng-model="search[searchBy]" /></td>
                    </tr>
                    <tr>
                        <td>بحث بإستخدام:</td>
                        <td>
                            <select ng-model="searchBy">
                                <option value="$"></option>
                                <option value="g_name">Guest Name</option>
                                <option value="g_tel">Guest Tel</option>
                                <option value="q_no">Question No.</option>
                            </select>
                        </td>
                    </tr>
                </table>
                <div>
                    <hr />
                </div>
                <table class="table table-bordered table-responsive">
                    <tr>
                        <td>م</td>
                        <td>التاريخ</td>
                        <td>الإسم</td>
                        <td>الهاتف</td>
                        <td>رقم السؤال</td>
                        <td>الإيجابة</td>
                    </tr>
                    <tr ng-repeat="w in Winners | filter:search| start: (currentPage - 1) * pageSize | limitTo: pageSize">
                        <td>{{$index + 1}}</td>
                        <td>{{w.g_date | mydate | date: 'dd/MM/yyyy'}}</td>
                        <td>{{w.g_name}}</td>
                        <td>{{w.g_tel}}</td>
                        <td>{{w.q_no}}</td>
                        <td>{{w.q_ans}}</td>

                    </tr>
                    <tr>
                        <pagination total-items="list.length" items-per-page="pageSize" ng-model="currentPage" max-size="5"
                                    class="pagination-sm"></pagination>
                    </tr>
                </table>
                
            </div>
        </div>
        <div class="col-md-5 alert alert-warning" role="alert">
            <div>
                <p style="font-size:20px;color:#000;font-weight:bold;">إسماء الفائزين العشرة بالمسابقة</p>
            </div>
            <div class="wlst">
                <table id="tbl">
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn1" value="الفائز الأول " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn2" value="الفائز الثاني " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn3" value="الفائز الثالث " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn4" value="الفائز الرابع " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn5" value="الفائز الخامس " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn6" value="الفائز السادس " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn7" value="الفائز السابع " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn8" value="الفائز الثامن " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn9" value="الفائز التاسع " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز العاشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز الحادي عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز الثاني عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز الثالث عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز الرابع عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز الخامش عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز السادس عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز السابع عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز الثامن عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز التاسع عشر " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="button" name="الفائز الأول" id="btn10" value="الفائز العشرون " class="btn btn-danger winl" /></td>
                        <td><span class="wname"></span></td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
   <script>
       $(function () {

           $(".winl").on("click", function () {
               //check to see if the button is clicked before and to do that we check for the class
               if ($(this).hasClass("btn-success")) {
                   alert("لقد تم إختيار الفائز من قبل");
                   return false;
               }
               $(this).removeClass("btn-danger");
               $(this).addClass("btn-success");
               var $na=$(this).closest("tr").find(".wname");
               var url = {
                   myurl : '@Url.Action("getName", "Winners")'
               }
               $.ajax({
                   type: "POST",
                   url: url.myurl,
                   data: "",
                   dataType: "Json",
                   success: function (data) {
                       $($na).text(data.g_name + "   " + data.g_tel);
                   }
               });
           });
       });
      
    </script> 
    }

Winners/Winners/Views/Winners/showAllWinners.cshtml
@{
    ViewBag.Title = "showAllWinners";
}

<h2>showAllWinners</h2>
<style>
    .active{
        color:red;
        font-weight:bold;
        padding:5px;
    }
</style>
<div>
    <div ng-controller="myController">
        <table>
            <tr>
                <td>Search:</td>
                <td><input type="text" ng-model="search[searchBy]" /></td>
            </tr>
            <tr>
                <td>Search By:</td>
                <td>
                    <select ng-model="searchBy">
                        <option value="$"></option>
                        <option value="g_name">Guest Name</option>
                        <option value="g_tel">Guest Tel</option>
                        <option value="q_no">Question No.</option>
                    </select>
                </td>
            </tr>
        </table>
        <table class="table table-bordered table-responsive">
            <tr>
                <td>م</td>
                <td>التاريخ</td>
                <td>الإسم</td>
                <td>الهاتف</td>
                <td>رقم السؤال</td>
                <td>الإيجابة</td>
            </tr>
            <tr ng-repeat="w in Winners | filter:search">
                <td>{{$index + 1}}</td>
                <td>{{w.g_date | mydate | date: 'dd/MM/yyyy'}}</td>
                <td>{{w.g_name}}</td>
                <td>{{w.g_tel}}</td>
                <td>{{w.q_no}}</td>
                <td>{{w.q_ans}}</td>
            </tr>
        </table>
    </div>
</div>